name = "sync-bookmarks-cron"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[triggers]
crons = ["*/5 * * * *"]

[env.production]
[env.production.triggers]
crons = ["*/5 * * * *"]

[env.staging]
[env.staging.triggers]
crons = ["*/5 * * * *"]